[package]
name = "clogbox-clap-egui"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
clogbox-enum.workspace = true
clogbox-clap = { workspace = true, features = ["gui"] }
clogbox-utils.workspace = true
log.workspace = true
serde_json.workspace = true

baseview = { git = "https://github.com/tomoyanonymous/baseview.git", rev = "d73e0b912c8c0f2989db6338fd5f07ec09ff4dd3" }
egui = { version = "0.33.3", features = ["persistence", "serde"] }
egui-baseview = { git = "https://github.com/BillyDM/egui-baseview.git", rev = "c5ad2f4bd094b100321a804122cf2218b43370da" }
