repos:
  - repo: https://github.com/berquist/pre-commit-rust
    rev: main
    hooks:
      - id: cargo-fmt
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.7
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format