[package]
name = "svfmixer"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
clogbox-core = { path = "../../crates/clogbox-core" }
clogbox-enum = { path = "../../crates/clogbox-enum" }
clogbox-filters = { path = "../../crates/clogbox-filters" }

clack-plugin = { git = "https://github.com/prokopyl/clack.git" }
clack-extensions = { git = "https://github.com/prokopyl/clack.git", features = ["clack-plugin", "audio-ports", "params",
    "state"] }