name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.name }}-${{ matrix.cross-target }}
      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make
      - name: Pre-build
        run: cargo make pre-build
      - name: Run clippy
        uses: clechasseur/rs-clippy-check@v3
        with:
          args: --workspace --all-targets --all-features
  ruff:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: [3.11, 3.12, 3.13]
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Test
        run: uvx ruff check python/clogbox
      - name: Cache venv
        uses: actions/cache@v4
        with:
          path: python/clogbox/.venv
          key: ${{ runner.os }}-py${{ matrix.python }}-uv
