name: Clippy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.name }}-${{ matrix.cross-target }}
      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run clippy
        uses: clechasseur/rs-clippy-check@v3
        with:
          args: --workspace --all-targets --all-features